### ISSUE TITLE
Problems with isoform mode

### ISSUE THREAD

**Issue by acarmas1** [DepledgeLab/DRUMMER#14] opened 2022-02-09 22:36 UTC
Hi, 

I tried to run drummer under the isoform mode, using this code: 

module load python3
module load anaconda3/2021.05
module load samtools/1.10
module load bedtools/2.27.1

python DRUMMER.py -r GCF_003254395.2_Amel_HAv3.1_genomic.fna \
-l overlap.txt \
-o isoform_DRUMMER \
-c alnWT_drum_isof_sort.bam \
-t alnKO_drum_isof_sort.bam -a isoform -m True

However, I got this erros:

RUNNING in isoform

Current Comparison: alnWT_drum_isof_sort.bam vs alnKO_drum_isof_sort.bam
Traceback (most recent call last):
  File "DRUMMER.py", line 74, in <module>
    test_isoform.main(transcriptome_file,treatment_bam,path_transcripts,control_bam,odds,padj,m6A,fraction_diff,visualization_input,output_dir,'isoform',del$
  File "/projects/dsn001/camila/programs/DRUMMER/modules/test_isoform.py", line 202, in main
    summary_df = run_summary(output_dir+'/'+repl + '/complete_analysis/',m6A_status)
  File "/projects/dsn001/camila/programs/DRUMMER/modules/summary.py", line 15, in run_summary
    onlydir = ['/'+f for f in listdir(target_dir) if isfile(join(target_dir, f))]
FileNotFoundError: [Errno 2] No such file or directory: 'isoform_DRUMMER/lnWT_drum_isof_-lnKO_drum_isof_/complete_analysis/'

Could someone help me to solve it, please.

Thanks,
Camila

**Comment by JonAbebe** [comment] 2022-02-10 12:35
Looks like the intermediate directory holding all isoform level dataframes does not exist. 
Could you do two things: 
1. Show me your overlap.txt file (just the first few lines)
2. Tell me the contents of isoform_DRUMMER.

**Comment by JonAbebe** [comment] 2022-02-10 23:08
Apologies, I meant the directory in which outputs go into, i.e. lnWT_drum_isof_lnKO_drum_isof_/. 
Which folders in this directory does not have data within them?, I simply want to find out which step DRUMMER is failing at.

**Comment by acarmas1** [comment] 2022-02-11 17:19
Within lnWT directory there is only a map directory
![image](https://user-images.githubusercontent.com/33578163/153638130-9e8fcb07-d2d1-4311-b217-7691402b1bca.png)

**Comment by JonAbebe** [comment] 2022-02-11 19:29
That's interesting. And you are sure that samtools and bedtools are in your path?
In the map folder there should be individual .bam files for each transcript.

**Comment by DepledgeLab** [comment] 2022-02-18 12:23
I just wanted to follow up on this - where you able to resolve the issue?

**Comment by acarmas1** [comment] 2022-02-18 16:58
No, drummer under the isoform mode is not working for me.
This is the code I used:
![image](https://user-images.githubusercontent.com/33578163/154727904-7f1a7350-efd6-476e-83b7-665ab616cd07.png)
I activated bedtools and samtools.

**Comment by acarmas1** [comment] 2022-02-18 16:59
Just in case, these are the first lines of the file overlap.txt 
![image](https://user-images.githubusercontent.com/33578163/154728192-b3f1e3c0-5e95-443f-9458-240268726265.png)

**Comment by DepledgeLab** [comment] 2022-02-18 17:19
Does isoform mode work with the test data provided in the repository?

_python DRUMMER.py -r TESTDATA/Ad5_v9.1_complete.fasta -l TESTDATA/Ad5.sample.transcripts.txt -o isoform-test -c TESTDATA/isoform.Ad5.MOD.bam -t TESTDATA/isoform.Ad5.UNMOD.bam -a isoform -m True

Can you also produce a long list (ll) of your DRUMMER directory and share a picture of this?

**Comment by DepledgeLab** [comment] 2022-02-19 10:24
Could you try run the isoform test data. The coding in this mode is slightly different so I would like to establish whether the problem is specific to your sample or just a general problem with running isoform mode.

I also notice you are using GCF_003254395.2_Amel_HAv3.1_genomic.fna as your reference file. Can you confirm this is a transcriptome rather than genome fasta (i.e. not the same file you used for exome mode)? The fasta headers in this file need to perfectly match the headers supplied in the overlap.txt file.

**Comment by acarmas1** [comment] 2022-02-20 18:12
I run the test data and it worked, so yes something is wrong with my inputs. 
GCF_003254395.2_Amel_HAv3.1_genomic.fna is the genome of Apis mellifera, so I'll change it.

Just to make sure, I have this file as transcriptome of honey bees, will it be okay to use it, or it need to be in another format?
![image](https://user-images.githubusercontent.com/33578163/154857437-eb607b19-74db-48a1-b509-c055d39967aa.png)

**Comment by DepledgeLab** [comment] 2022-02-21 10:10
For both exome and isoform mode, DRUMMER requires the same fasta file that was used in the alignment. In the case of exome analysis, this should be a genome file and for isoform mode this should be the transcriptome file. The screenshot you just shared does look correct for isoform mode (i.e. a transcriptome fasta) so it should now run correctly.

It's possible DRUMMER won't like the spaces in the FASTA header lines. **_If_** that is the case then you can also parse you transcriptome file as follows: _sed 's/ .*//g' file.fasta > file.fixed.fasta_ where _file_ should be the name of your transcriptome fasta (minus the .fasta part). This code looks at each line in the file and when it finds a space, removes that space and any following text leading to the end of that line.

**Comment by FDallaPozza** [comment] 2022-02-21 11:53
Hi! I'm having the same kind of problem working on my data. As adviced I tried to create the file.fixed.fasta but still I got the same error:
 
(Traceback (most recent call last):
  File "../DRUMMER/DRUMMER.py", line 74, in <module>
    test_isoform.main(transcriptome_file,treatment_bam,path_transcripts,control_bam,odds,padj,m6A,fraction_diff,visualization_input,output_dir,'isoform',deletion)
  File "/Users/fabiodallapozza/Desktop/DRUMMER/modules/test_isoform.py", line 202, in main
    summary_df = run_summary(output_dir+'/'+repl + '/complete_analysis/',m6A_status)
  File "/Users/fabiodallapozza/Desktop/DRUMMER/modules/summary.py", line 15, in run_summary
    onlydir = ['/'+f for f in listdir(target_dir) if isfile(join(target_dir, f))]
FileNotFoundError: [Errno 2] No such file or directory: 'm6A_detection/WT3_basecall-KO3_basecall/complete_analysis/').

**Comment by DepledgeLab** [comment] 2022-02-21 12:17
Could you specify the full command you used to run DRUMMER with the test data set? Did it fail in both exome and isoform modes?

**Comment by FDallaPozza** [comment] 2022-02-21 13:02
This is the command I used for the exome (which gave me the error of the previous message):

python DRUMMER.py -r TESTDATA/Adenovirus-Ad5.fasta -n Ad5 -o exome-test -c TESTDATA/exome.Ad5.MOD.bam -t TESTDATA/exome.Ad5.UNMOD.bam -a exome -m True

While this one is the command for the isoform:

python DRUMMER.py -r TESTDATA/Ad5_v9.1_complete.fasta -l TESTDATA/Ad5.sample.transcripts.txt -o isoform-test -c TESTDATA/isoform.Ad5.MOD.bam -t TESTDATA/isoform.Ad5.UNMOD.bam -a isoform -m True

With this one I got this error: 

Current Comparison: TESTDATA/isoform.Ad5.MOD.bam vs TESTDATA/isoform.Ad5.UNMOD.bam
Traceback (most recent call last):
  File "DRUMMER.py", line 74, in <module>
    test_isoform.main(transcriptome_file,treatment_bam,path_transcripts,control_bam,odds,padj,m6A,fraction_diff,visualization_input,output_dir,'isoform',deletion)
  File "/Users/fabiodallapozza/Desktop/DRUMMER/modules/test_isoform.py", line 202, in main
    summary_df = run_summary(output_dir+'/'+repl + '/complete_analysis/',m6A_status)
  File "/Users/fabiodallapozza/Desktop/DRUMMER/modules/summary.py", line 15, in run_summary
    onlydir = ['/'+f for f in listdir(target_dir) if isfile(join(target_dir, f))]
FileNotFoundError: [Errno 2] No such file or directory: 'isoform-test/isoform.Ad5.MOD-isoform.Ad5.UNMOD/complete_analysis/'

**Comment by DepledgeLab** [comment] 2022-02-21 13:28
This is curious - the commands you specify work perfectly on my system. 

Can you confirm that samtools and bedtools are loaded (+ specify versions) and also let me know which version of python3 you are using?

**Comment by MaestSi** [comment] 2022-02-21 15:14
Hi, here is the command I used:
`python DRUMMER.py -r TESTDATA/Adenovirus-Ad5.fasta -n Ad5 -o exome-test -c TESTDATA/exome.Ad5.MOD.bam -t TESTDATA/exome.Ad5.UNMOD.bam -a exome -m True`
And this is the error I got:

```
SAMTOOLS in path
Bedtools in path


     ________________________________
    | __   __                 __  __ |
    ||  \ |_/ |  | |\/| |\/| |_  |_/ |
    ||__/ | \ |__| |  | |  | |__ | \ |
    |________________________________|
    

RUNNING in exome

Current Comparison: TESTDATA/exome.Ad5.UNMOD.bam vs TESTDATA/exome.Ad5.MOD.bam
Traceback (most recent call last):
  File "DRUMMER.py", line 55, in <module>
    test_exome.main(transcriptome_file,treatment_bam,name,control_bam,odds,padj,m6A,fraction_diff,output_dir,'exome',deletion)
  File "/Users/simonemaestri/Software/DRUMMER/modules/test_exome.py", line 194, in main
    summary_df = run_summary(output_dir+'/'+repl + '/complete_analysis/',m6A_status)
  File "/Users/simonemaestri/Software/DRUMMER/modules/summary.py", line 41, in run_summary
    final_candidates = all_candidates[keep_columns]
  File "/Users/simonemaestri/miniconda3/envs/DRUMMER_env/lib/python3.7/site-packages/pandas/core/frame.py", line 2908, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/Users/simonemaestri/miniconda3/envs/DRUMMER_env/lib/python3.7/site-packages/pandas/core/indexing.py", line 1254, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "/Users/simonemaestri/miniconda3/envs/DRUMMER_env/lib/python3.7/site-packages/pandas/core/indexing.py", line 1298, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['chr_ctrl', 'ref_ctrl', 'pos_ctrl', 'depth_ctrl', 'depth_treat',\n       'ref_fraction_ctrl', 'ref_fraction_treat', 'frac_diff', 'odds_ratio',\n       'log2_(OR)', 'p_values_OR_adj', 'eleven_bp_motif', 'G_test', 'padj',\n       'accumulation', 'depletion', 'nearest_ac', 'nearest_ac_motif',\n       'homopolymer', 'is_SNP'],\n      dtype='object')] are in the [columns]"

```

**Comment by JonAbebe** [comment] 2022-02-21 15:46
Below is my output of a DRUMMER run with the test data from a few minutes ago.
Looks like the problem is stemming from the initial mapping step. 
Could you try some arbitrary samtools/bedtools command to make sure these are working correctly.

Maybe..
samtools view -b TESTDATA/exome.Ad5.MOD.bam Ad5:1-5000 -o test.out.bam
bedtools genomecov -d -split -ibam test.out.bam > test.coverage.bed

<img width="1324" alt="Screen Shot 2022-02-21 at 10 31 29 AM" src="https://user-images.githubusercontent.com/31824906/154985724-5c0ea246-7d44-4cdf-bf47-7ffbf55e249d.png">

**Comment by MaestSi** [comment] 2022-02-21 15:48
<img width="194" alt="image" src="https://user-images.githubusercontent.com/19406763/154987920-59c898d2-4091-4fc6-ac08-5134fe8a404a.png">
Hi, it looks like they are working. Here is a screenshot of a portion of rest.coverage.bed file.

Thanks,
SImone

**Comment by JonAbebe** [comment] 2022-02-21 16:02
So samtools/bedtools is not the problem, let's see which downstream command may be causing the issue.
Could you run the tree command. I want to see what outputs (if any you are getting).

tree exome-test/

If all is well, it should look like this.
<img width="280" alt="Screen Shot 2022-02-21 at 11 00 31 AM" src="https://user-images.githubusercontent.com/31824906/154990029-1b0c363c-d3af-4661-83e7-ab399bb26742.png">

**Comment by MaestSi** [comment] 2022-02-21 16:04
<img width="725" alt="image" src="https://user-images.githubusercontent.com/19406763/154990538-a352011f-586f-47ac-98b4-840779b817b4.png">

Here it is!
Simone

**Comment by JonAbebe** [comment] 2022-02-21 16:20
Hmm.. That's interesting, in bam_readcount you should have 2 files for each condition (UNMOD and MOD), also I am curious why there is no index file for Ad5.fa.

Last request, could you use this command to see the sizes of mapped files (I suspect a few of them are empty). This should tell us if the mapping is the issue or bamreadcount command.

ls -lh map

**Comment by FDallaPozza** [comment] 2022-02-21 16:23
Hi, 
I think I solved my problems on the test data just running all the commands on Ubuntu, before I was running them on the Mac's terminal, and this seems to be the problem. Just out of curiosity, isn't there a way to use the commands on Mac or it can be done only on Ubuntu?

**Comment by MaestSi** [comment] 2022-02-21 16:26
<img width="763" alt="image" src="https://user-images.githubusercontent.com/19406763/154993970-848acbe6-910c-4fc8-9d19-6eed58ae6978.png">

Here it is. By the way, I'm running on Mac too.
Simone

**Comment by DepledgeLab** [comment] 2022-02-21 16:37
The absence of the indexed fasta file is odd. Can you generate this yourself and rerun the command. Can you also remove the hyphen from the output dir name? I suspect there is something odd happening with the mac terminal....

**Comment by acarmas1** [comment] 2022-02-21 19:06
Hi,

Regarding to my error, I applied sed 's/ .*//g' file.fasta > file.fixed.fasta to my trancriptome and run DRUMMER in the isoform mode, with this code:
![image](https://user-images.githubusercontent.com/33578163/155013606-810408f4-fee6-45a5-8e42-5246b746f348.png)
I got this error: 
![image](https://user-images.githubusercontent.com/33578163/155013540-1e1e8d04-beed-4fd3-bdec-6b9c9905605f.png)
However, then I looked into the rna directory a summary.txt was created, and it looks like this:
![image](https://user-images.githubusercontent.com/33578163/155013778-e92b6611-3f71-453e-8332-34ae456c6995.png)

**Comment by DepledgeLab** [comment] 2022-02-21 19:24
This is looking good. The output certainly looks correct. 

The error might result from an empty line at the end of the overlap_rna.txt file. I'll look into this shortly.

**Comment by DepledgeLab** [comment] 2022-02-25 14:00
> Hi, I think I solved my problems on the test data (which are the same of @MaestSi) just running all the commands on Ubuntu, before I was running them on the Mac's terminal, and this seems to be the problem. Just out of curiosity, isn't there a way to use the commands on Mac or it can be done only on Ubuntu?

With regard to this, we have learned that the bam-readcount package included in DRUMMER is not compatible with OSX systems (see https://github.com/genome/bam-readcount/blob/master/BUILD.md). We are now testing the latest release of bam-readcount to see if this can be resolved. For now though I recommend sticking with UNIX systems only.

**Comment by FDallaPozza** [comment] 2022-03-02 15:01
Hi,
I solved the problem that I had in the previous message about multiple replicates, it seems that there is also a problem when in the header of a fasta file there are underscores (_), without them (and without whitespaces) everything is working good also with my data.

Fabio

**Comment by DepledgeLab** [comment] 2022-03-02 18:44
Hi Fabio,

Thanks for the update and for flagging this issue. We'll work on fix for the underscore issue but in the meantime I am glad the workaround is functional.

I'll go ahead and close this issue now but feel free to raise a new one if any other problems crop up.

**Closed by DepledgeLab** 2022-03-02 18:44 UTC
