### ISSUE TITLE
Understanding options and outputs

### ISSUE THREAD

**Issue by rania-o** [DepledgeLab/DRUMMER#19] opened 2022-07-18 15:19 UTC
Hello,
Thank you for developing this tool.
I have few questions about the options used for the detection.

First, I would like to know if the option "odd ratio" plays a role or no ? because I used the default option (= +/- 1.5) and as results I have a lot of positions that have an odd ratio < 1.5 but are not negative, is it normal ? because according to the paper " The modified positions are candidates if the p-values of the G-test and the odd ratio are lower than the user's threshold (default 0.05) and the odd ratio exceeds the user's threshold (default > 1.5)".

For the option "reference fraction difference (=0.01), does it mean that the positions that have an inferior value are not token into account ? (which is not valid for me, because I have as results a lot of positions with a fraction difference superior and inferior to 0.01)

 I also run my samples with 2 different depths to see if it has an effect on the results, and I've found some differences. But for one position, it came out as a candidate site for one depth (3 000X) but not for the other depth (36 000X). I had these results as you can see :

`SEQUENCE	7350	A	1648	1357	12	12	213	54	0.8234223300970874	SEQUENCE	A	36802	28324	200	264	6632	1382	0.7696320852127602	3.340882283557443	-0.053790244884327265	4.6632302405498285	0.4811005124985208	0.7164309097385526	1.9985378332673226e-07	CAACA	GATCAACAGCT	33	1.1727027923655597e-06	0.0106352416239632	0.0018124739609901`

`SEQUENCE	7350	A	1648	1357	12	12	213	54	0.8234223300970874	SEQUENCE	A	3556	2686	28	21	691	130	0.7553430821147357	3.0873563218390805	-0.06807924798235176	4.6632302405498285	0.5949576638192187	0.662063883312581	2.7792959522921196e-08	CAACA	GATCAACAGCT	36	2.325350074067185e-07	0.0021088599821715	0.0002520543499133		accumulation`

Thank you for your help,
Rania

**Comment by DepledgeLab** [comment] 2022-07-20 05:03
Hi Rania,

DRUMMER calculates the odds ratio for each test and we subsequently transform this with log2. Candidate sites are those which have a log2 Odds Ratio < -1.5 or > 1.5 and a G-test score with an adjusted p-value < 0.05.

For reference fraction difference, we determine the difference in reported error rate between the two samples. In your first provided example the reference fraction difference = -0.05379 (0.7696 - 0.8234). By default, DRUMMER only considers sites with the reference fraction difference of < -0.01 or > 0.01. The idea is to not consider sites with effectively the same error rate (i.e. refence fraction difference between -0.01 and 0.01.

As for the last part, we have observed that a large (> 2-3 fold) difference in sequencing depths between samples reduces sensitivity, presumably as a function of how the G-test works. The optimal approach is thus to compare two samples at a similar read depth and then use subsampling approaches on both the address saturation.

Hope that helps

Dan

**Comment by rania-o** [comment] 2022-07-20 09:05
Hello Dan,

Thanks for your fast reply.
I still don't understand why a position with an adjusted p-value < 0.05  is not considered by Drummer as a candidate site : 

`SEQUENCE 7350 A 1648 1357 12 12 213 54 0.8234223300970874 SEQUENCE A 36802 28324 200 264 6632 1382 0.7696320852127602 3.340882283557443 -0.053790244884327265 4.6632302405498285 0.4811005124985208 0.7164309097385526 1.9985378332673226e-07 CAACA GATCAACAGCT 33 1.1727027923655597e-06 0.0106352416239632 0.0018124739609901`

As for the log2 odd ratio, I also have candidate sites that have a log2 Odd Ratio >-1.5 and <1.5 but with a significant p-value, like this one for example:

`SEQUENCE	4820	A	641	596	1	0	34	10	0.9297971918876756		SEQUENCE  A	3359	2778	2	5	467	107	0.8270318547186662	4.781411359724613	-0.10276533716900937	13.244444444444444	1.4698788935556228	0.3610126026637711	1.5936846582375017e-12	GGACA	GCAGGACATAA	54	6.409434204402394e-11	5.812715879972532e-07	1.4453126165555904e-08		accumulation`

So according to my results : "Candidate sites are those which have a log2 Odds Ratio < -1.5 or > 1.5  **OR**  a G-test score with an adjusted p-value < 0.05" ?

Thanks for your help,
Rania

**Comment by JonAbebe** [comment] 2022-07-20 14:12
Hi Rania,

DRUMMER requires three conditions to call a candidate site (default parameters).
1: adjusted p-value of < 0.05
2: Reference fraction difference of < -0.01 or > 0.01
3: Odds Ratio > 1.5 for a site to be called 'depleted', Odds Ratio < 1/(1.5) for a site to be called 'accumulation'

I attached an example which should show this (with the irrelevant columns deleted).
As you can see, both sites 
1: have a padj <0.05
2: have frac_diff of <-0.01 or >0.01
3: finally, the first site has an odds_ratio value of 1.95 so it is called 'depleted' while the second site has an odds_ratio value of 0.63 which is called 'accumulation'.

Happy to help if there are additional questions.

Jonathan


[L2-Penton.complete.txt](https://github.com/DepledgeLab/DRUMMER/files/9150588/L2-Penton.complete.txt)

**Comment by rania-o** [comment] 2022-07-22 07:36
Hello @JonAbebe,

Thank you for your reply and sorry to bother you again.
I understood all of the three conditions to call a candidate site, but my question was about a position that has all of these conditions but still didn't show up as a candidate site in the results. 

Another question about the odd ratio (that maybe I misunderstood), according to Dan's answer, the value of the **log2odd ratio**  should be < -1.5 or > 1.5, but in your answer you're talking about the value of the **odd ratio** that should be > 1.5 or < 1/(1.5). Does it means the same thing ?

Rania

**Comment by JonAbebe** [comment] 2022-07-22 17:25
Hi Rania,

It is no bother at all.
Could you put your data in a table with columns labeled so I can confirm I am looking at the correct values?

Looking at the column values I believe they have been slightly mislabeled, i.e. log2_(OR) is not completely accurate. 
The odds_ratio column uses the fisher exact test which shows how much error WT sequence has over the unmodified sequence. An odds_ratio value of 1 means no real difference between the two conditions. A value of >1.5 (default) shows that this WT position has more error than this unmodified position. The odds ratio cannot be negative, but the inverse is true. If a value is below 1 it means the negative case is true, in our case that this unmodified position has more error than this WT position. So for positions where odds_ratio is less than 1, we use a value of <0.667 or 1/1.5 to establish 'accumulation' sites (error in unmodified is greater than the error in WT).

In a previous iteration of DRUMMER we used to use log2FC to help call sites but we got rid of it. But for your information, the log2_(OR) value is calculated positionally by calculating the ratio of the most abundant nucleotide and the sum of all nucleotides at that position. This ratio is calculated for both WT and unmodified conditions. A fold change (FC) is calculated by dividing these two numbers (from each condition) and finally we take the -log2(FC) to get the final value. But again, the value is not used to make candidate calls anymore.

Hopefully that helps clarify things,

Jonathan

**Comment by rania-o** [comment] 2022-08-02 08:25
Hi @JonAbebe,

Thank you for your reply and sorry for the late reply.
Please find attached an example of the position I was talking about, and please tell me if it is normal to have these values when the position is not considered modified.

Rania

[example_results.txt](https://github.com/DepledgeLab/DRUMMER/files/9240367/example_results.txt)

**Comment by JonAbebe** [comment] 2022-08-03 13:27
Hi Rania,

Could you double check the columns - looks like something is off about them. For example, the 'frac_diff' column should be a numerical value, not a nucleotide. Maybe you can just extract these position from the DRUMMER output?

Thanks.

Jonathan

**Comment by rania-o** [comment] 2022-08-03 13:44
Hi @JonAbebe,

In the previous file, I just deleted the "ref" header for the nucleotide column.
In this file, I copied the output from DRUMMER :
[drummer_results.txt](https://github.com/DepledgeLab/DRUMMER/files/9251817/drummer_results.txt)

Thank you.

Rania

**Comment by JonAbebe** [comment] 2022-08-03 18:18
Seems like the column labels have been shifted to the left somehow., looks like it is because 'chr_treat' and 'ref_treat' column names have been merged somehow. 
For example, the 'depth_treat' column has a value of 'A' - but if you shift it to the right it has a value of 36802, which is indeed the sum of all the nucleotide counts at that position, i.e. the depth at that position. 

All to say, I suggest shifting the columns, beginning from 'depth_threat', to the right by one. After that, I believe the results will make sense.
The first site has an odds_ratio value of .716 which is not below the .6667 threshold - thus not considered a modified site.
The second site has an odds_ratio value of .662 which is barely below the .6667 threshold - thus is correctly called an 'accumulation' site.

Let me know if something is unclear.

Jonathan

**Comment by rania-o** [comment] 2022-08-05 14:42
Hi @JonAbebe ,

Thank you very much for all these explanations.
It helps me a lot to understand better the results of Drummer.

Rania

**Comment by JonAbebe** [comment] 2022-08-08 17:51
Of course, glad I could help.

Jonathan

**Closed as completed by JonAbebe** 2022-08-08 17:51 UTC
